routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LinkController;
use App\Http\Controllers\TagController;
use App\Http\Controllers\LinkRedirectController;
use App\Http\Controllers\LinkStatisticController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('mainPage');
})->name("mainPage");
Route::resources([
    'links' => LinkController::class,
    'tags' => TagController::class,
]);

Route::get('/statistics', [LinkStatisticController::class, "index"])->name("statistics");

Route::get('/{shortLink}', [LinkRedirectController::class, 'redirect']);

app/Models/Link.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Link extends Model
{
    use HasFactory;

    protected $fillable = [
        'short_link', 'long_link', 'title'
    ];

    public function tags(): BelongsToMany
    {
        return $this->belongsToMany(Tag::class);
    }

    public function statistics()
    {
        return $this->hasMany(LinkStatistic::class);
    }

    public function sort($param = [["updated_at", "desc"]])
    {
          return  $this->statistics
              ->sortBy($param)
              ->all();
    }
}

app/Http/Controllers/LinkController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\LinkRequest;
use App\Models\Link;
use App\Models\Tag;
use App\Rules\ValidUrl;
use App\Services\ShortLink\ShortLink;
use Illuminate\Http\Request;

class LinkController extends Controller
{
    private $shortLink;

    public function __construct(ShortLink $shortLink)
    {
        $this->shortLink = $shortLink;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\View\View
     */
    public function index()
    {
        $links = Link::all();
        return view("links.index", compact("links"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        $tags = Tag::pluck('name', 'id')->all();
        return view("links.create", compact("tags"));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\LinkRequest  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(LinkRequest $request)
    {
        $data = $request->validated();
        $data["short_link"] = $this->shortLink->generate();
        $link = new Link();
        $link->fill($data);
        $link->save();
        $link->tags()->sync($request->tags);
        return redirect()->route('links.index')->with('success', 'Ссылка добавлена!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Link  $link
     * @return \Illuminate\View\View
     */
    public function show(Link $link)
    {
        return view("links.show", compact("link"));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Link  $link
//     * @return \Illuminate\Http\Response
     */
    public function edit(Link $link)
    {
        $tags = Tag::pluck('name', 'id')->all();
        return view('links.edite', compact('link',  'tags'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\LinkRequest  $request
     * @param  \App\Models\Link  $link
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(LinkRequest $request, Link $link)
    {
        $data = $request->validated();
        $link->update($data);
        $link->tags()->sync($request->tags);
        return redirect()->route('links.index')->with('success', 'Ссылка обновлена!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Link  $links
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Link $link)
    {
        $link->delete();
        return redirect()
            ->route('links.index')->with('success', 'Link deleted successfully!');
    }
}

resources/views/links/create.blade.php
@extends('layouts.app')

@section('content')
    <h1>Create link</h1>
    @if ($errors->any())
        <div>
            <ul>
                @foreach ($errors->all() as $error)
                    <li class="text-danger">{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form method="POST" action="{{ route("links.store") }}">
        @csrf
        <div class="form-group mb-3">
            <label for="Title" class="form-label">Title</label>
            <input type="text" name="title" class="form-control  @error('title') is-invalid @enderror" id="Title">
        </div>
        <div class="form-group mb-3">
            <label for="Link" class="form-label">Link</label>
            <input type="text" name="long_link" class="form-control @error('long_link') is-invalid @enderror" id="Link">
        </div>

        <div class="form-group">
            <label for="tags">Tags</label>
            <select class="form-control" data-placeholder="Choose tags" id="tags" name="tags[]" multiple="multiple">
                @foreach($tags as $id => $tag)
                    <option value="{{$id}}" @if (old('tag_id')==$id) selected @endif>
                        {{$tag}}
                    </option>
                @endforeach
            </select>
        </div>
        <button type="submit" class="btn btn-primary mt-5">Submit</button>
    </form>

@endsection

resources/views/links/edite.blade.php
@extends('layouts.app')

@section('content')
    <h1>Edite link</h1>
    @if ($errors->any())
        <div>
            <ul>
                @foreach ($errors->all() as $error)
                    <li class="text-danger">{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form method="POST" action="{{ route("links.update", ["link" => $link->id]) }}">
        @csrf
        @method('PUT')
        <div class="form-group mb-3">
            <label for="Title" class="form-label">Title</label>
            <input type="text" name="title" class="form-control" id="Title" value="{{ $link->title }}">
        </div>
        <div class="form-group mb-3">
            <label for="Link" class="form-label">Link</label>
            <input type="text" name="long_link" class="form-control" id="Link" value="{{ $link->long_link }}">
        </div>

        <div class="form-group">
            <label for="tags">Tags</label>
            <select class="form-control" data-placeholder="Choose tags" id="tags" name="tags[]" multiple="multiple">
                @foreach($tags as $id => $tag)
                    <option @if (in_array($id, $link->tags->pluck('id')->all())) selected @endif
                    value="{{$id}}">{{$tag}}</option>
                @endforeach
            </select>
        </div>
        <button type="submit" class="btn btn-primary mt-5">Submit</button>
    </form>

@endsection

resources/views/links/index.blade.php
@extends('layouts.app')

@section('content')
    <h1>Links index</h1>
    <a class="btn btn-primary mb-5 mt-5" href="{{ route("links.create") }}" role="button">Create link</a>

    <table class="table table-striped table-bordered">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Title</th>
            <th scope="col">Short link</th>
            <th scope="col">Long link</th>
            <th scope="col">Tags</th>
            <th scope="col">Date</th>
            <th scope="col">Action</th>
        </tr>
        </thead>
        <tbody>
        @forelse ($links as $key => $link)
            <tr>
                <th>{{ $key + 1 }}</th>
                <td>{{ $link->title }}</td>
                <td><a href="/{{ $link->short_link }}" target="_blank">{{ $link->short_link }}</a></td>
                <td>{{ $link->long_link }}</td>
                <td>{{$link->tags->pluck('name')->join(', ')}}</td>
                <td>{{ $link->updated_at }}</td>
                <td style="white-space: nowrap; ">
                    <a class="btn btn-primary btn-sm float-left mr-1"
                       href="{{ route("links.show", ['link' => $link->id]) }}">
                        <i class="fa fa-eye" aria-hidden="true"></i>
                    </a>
                    <a class="btn btn-primary btn-sm float-left mr-1"
                       href="{{ route("links.edit", ['link' => $link->id]) }}">
                        <i class="fa fa-pencil" aria-hidden="true"></i>
                    </a>
                    <form action="{{ route('links.destroy', $link) }}" method="post"
                          class="float-left d-inline-block" title="Удалить">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger btn-sm"
                                onclick="return confirm('Подтвердите удаление')">
                            <i class="fa fa-trash" aria-hidden="true"></i>
                        </button>
                    </form>
                </td>
            </tr>
        @empty
            <td>No links</td>
        @endforelse

        </tbody>
    </table>
@endsection

resources/views/links/show.blade.php
@extends('layouts.app')

@section('content')
    <h1>Show link</h1>

    <p>Link title: {{ $link->title }}</p>
    <p>Short link: <a href="/{{ $link->short_link }}" target="_blank">{{ $link->short_link }}</a></p>
    <p>Long link: {{ $link->long_link }}</p>
    <p>Link Tags: {{$link->tags->pluck('name')->join(', ')}}</p>
    <p>Link Date: {{ $link->updated_at }}</p>

    <a class="btn btn-primary mt-5 mb-5"
       href="{{ route("links.edit", ["link" => $link->id]) }}"
       role="button">Edite link</a>

    <h1>Show link statistic</h1>
    <p>Total views: {{ $link->statistics->count() }}</p>

    <table class="table table-striped table-bordered">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Title</th>
            <th scope="col">Short link</th>
            <th scope="col">Long link</th>
            <th scope="col">Tags</th>
            <th scope="col">User agent</th>
            <th scope="col">User ip</th>
            <th scope="col">Date</th>
        </tr>
        </thead>
        <tbody>
        @forelse ($link->sort() as $key => $stat)
            <tr>
                <th>{{ $key + 1 }}</th>
                <td>{{ $link->title }}</td>
                <td><a href="/{{ $link->short_link }}" target="_blank">{{ $link->short_link }}</a></td>
                <td>{{ $link->long_link }}</td>
                <td>{{$link->tags->pluck('name')->join(', ')}}</td>
                <td>{{ $stat->user_agent }}</td>
                <td>{{ $stat->user_ip }}</td>
                <td>{{ $stat->updated_at }}</td>
            </tr>
        @empty
            <td>No links</td>
        @endforelse

        </tbody>
    </table>

@endsection